# -*- coding: utf-8 -*-
"""Middle Cohort T-Tests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1CEBKqAw4RGamiP694m4K7NMoQTj6Ck
"""

import numpy as np
from scipy.stats import ttest_ind

                                                      # iRBD Patients To Healthy Controls


# Entropy of Speech Timing (iRBD Patients to Healthy Controls) | Insignificant

estScoreReading2 = [1.564, 1.551, 1.541, 1.56, 1.564, 1.552, 1.559, 1.565, 1.468, 1.534, 1.559, 1.556, 1.485, 1.537]
estScoreMonologue2 = [1.568, 1.555, 1.56, 1.535, 1.541, 1.563, 1.555, 1.543, 1.536, 1.544, 1.556, 1.567, 1.547, 1.55]

estScoreReading3 = [1.546, 1.558, 1.544, 1.563, 1.557, 1.508, 1.557, 1.558, 1.554, 1.549, 1.545, 1.561, 1.54, 1.552]
estScoreMonologue3 = [1.542, 1.557, 1.53, 1.564, 1.574, 1.512, 1.558, 1.56, 1.556, 1.551, 1.563, 1.568, 1.537, 1.566]

# Rate of Speech Timing (iRBD Patients to Healthy Controls) | Both Reading and Monologue Scores Are Significant

rstScoreReading2 = [359, 358, 270, 285, 278, 342, 361, 354, 293, 337, 296, 294, 317, 297]
rstScoreMonologue2 = [286, 273, 288, 234, 247, 286, 273, 273, 246, 259, 269, 307, 255, 266]

rstScoreReading3 = [392, 417, 335, 389, 381, 329, 372, 354, 303, 360, 328, 350, 298, 264]
rstScoreMonologue3 = [347, 294, 314, 290, 412, 301, 367, 235, 275, 268, 330, 315, 246, 281]

# Acceleration of Speech Timing (iRBD Patients to Healthy Controls) | Insignificant

astScoreReading2 = [37.62, 16.54, 38.15, 7.3, 13, 2.54, 12.31, 19.01, 5.07, 21.35, 4.4, 30.59, 9.15, 4.46]
astScoreMonologue2 = [-1.89, 7.01, -4.21, -5.3, -17.87, 0.97, 3.21, 0.93, -0.78, -2.74, 0.21, -2.59, 0.7, 4.61]

astScoreReading3 = [-9.4, 40.07, 8.91, 7.35, 11.33, 18.73, 23.33, 13.85, 14.34, 17.37, -15.82, -20.32, -13.66, 6.49]
astScoreMonologue3 = [11.65, -6.1, 1.05, -4.01, 2.6, 3.02, 3.62, 8.86, 1.22, 1.74, -3.25, 5.04, 5.09, 0.24]

# Duration of Pause Intervals (iRBD Patients to Healthy Controls) | Insignificant

dpiScoreReading2 = [135, 111, 175, 250, 181, 153, 145, 126, 226, 162, 245, 177, 147, 185]
dpiScoreMonologue2 = [221, 167, 224, 404, 169, 211, 260, 217, 245, 271, 253, 191, 186, 178]

dpiScoreReading3 = [109, 117, 159, 145, 130, 129, 96, 140, 176, 196, 168, 154, 177, 171]
dpiScoreMonologue3 = [226, 219, 179, 285, 152, 139, 117, 233, 270, 298, 197, 184, 223, 235]

# Duration of Voiced Intervals (iRBD Patients to Healthy Controls) | Reading Scores are Insignificant, Monologue Scores Are Significant

dviScoreReading2 = [264, 261, 332, 303, 327, 271, 258, 273, 284, 288, 267, 335, 313, 274]
dviScoreMonologue2 = [322, 364, 302, 318, 392, 342, 324, 308, 347, 348, 348, 284, 360, 317]

dviScoreReading3 = [245, 229, 284, 240, 248, 336, 255, 252, 298, 228, 264, 260, 283, 354]
dviScoreMonologue3 = [258, 305, 311, 259, 211, 360, 274, 341, 295, 286, 275, 269, 391, 319]

# Gaping In-Between Voiced Intervals (iRBD Patients to Healthy Controls) | Insignificant

gibviScoreReading2 = [61.22, 69.57, 69.34, 39.27, 55.71, 51.11, 47.17, 69.08, 28.83, 35.17, 56.43, 49.36, 21.09, 61.76]
gibviScoreMonologue2 = [50.47, 40.98, 48.77, 29.32, 30.97, 42.91, 34.7, 41.71, 28.73, 28.56, 27.13, 59.45, 37.84, 58.27]

gibviScoreReading3 = [43.72, 59.33, 38, 53.89, 72.14, 38.36, 79.37, 54.37, 45.21, 46.13, 38.54, 53.61, 53.01, 35.59]
gibviScoreMonologue3 = [32.87, 35.46, 26.16, 42.95, 72.56, 22.71, 52.62, 63.91, 41.81, 39.87, 44.18, 58.73, 37.74, 44.56]

# Duration of Unvoiced Stops (iRBD Patients to Healthy Controls) | Insignificant

dusScoreReading2 = [38.12, 38.13, 50.5, 25.75, 26.88, 24.63, 24.62, 22.38, 64, 29.13, 29.13, 24.63, 42.63, 35.88]
dusScoreMonologue2 = [22.38, 22.38, 31.37, 35.88, 35.88, 22.37, 31.37, 49.37, 35.88, 35.87, 22.38, 26.87, 35.88, 29.13]

dusScoreReading3 = [22.38, 28, 28, 40.37, 25.75, 20.13, 42.62, 24.63, 29.13, 24.63, 40.37, 24.62, 50.5, 29.13]
dusScoreMonologue3 = [22.38, 31.37, 26.88, 26.88, 17.88, 22.38, 22.38, 26.88, 22.38, 31.37, 31.37, 26.88, 40.37, 26.88]

# Duration of Unvoiced Fricatives (iRBD Patients to Healthy Controls) | Monologue Scores Are Insignificant, Reading Scores Are Significant

dufScoreReading2 = [0.073, -0.893, -0.297, -0.438, -3.457, -1.392, -2.492, 0.356, 5.013, -2.466, -1.372, 0.92, 1.389, 0.835]
dufScoreMonologue2 = [-0.449, 0.466, -0.483, 0.428, 1.916, -0.275, -0.134, -0.013, 0.154, 0.789, 0.241, 1.487, 0.286, -0.347]

dufScoreReading3 = [-4.831, -0.302, -0.292, -1.857, -0.47, -0.878, -2.238, -5.462, 1.004, -3.081, -2.613, -4.169, -1.111, -0.469]
dufScoreMonologue3 = [-0.448, -0.406, 0.01, -0.328, -0.758, 0.181, -0.664, 0.438, -0.172, 1.027, 0.781, -0.385, 0.411, 1.137]

# Relative Loudness of Respiration (iRBD Patients to Healthy Controls) | Insignificant

rlrScoreReading2 = [-24.73, -18.81, -18.01, -19.66, -20.87, -25.41, -22.85, -24.17, -23.37, -20.25, -30.48, -23.55, -18.09, -15.32]
rlrScoreMonologue2 = [-15.73, -17.91, -13.99, -19.33, -16.26, -24.48, -23.13, -20.04, -20.16, -20.99, -23.91, -20.88, -20.91, -19.73]

rlrScoreReading3 = [-18.25, -16.28, -27.46, -21.06, -22.32, -16.81, -19.52, -17.16, -29.11, -22.57, -27.62, -23.28, -22.91, -28.26]
rlrScoreMonologue3 = [-23.69, -12.46, -21.32, -21.65, -17.66, -16.74, -14.34, -17.68, -22.68, -20.42, -19.87, -19.08, -15.56, -27.31]

# Pause Intervals per Respiration (iRBD Patients to Healthy Controls) | Both Reading and Monologue Scores Are Significant

piprScoreReading2 = [7.5, 6.25, 4.5, 3.5, 5.5, 4.75, 4.75, 8, 2, 3.25, 3.25, 5.5, 4, 5.5]
piprScoreMonologue2 = [4.5, 4, 4, 2, 4, 3.5, 4, 3, 3, 3, 3, 5, 3, 5]

piprScoreReading3 = [8, 10, 3.5, 6.75, 8, 9, 17.25, 4.5, 4.75, 5.5, 3.75, 9.5, 4.5, 4.5]
piprScoreMonologue3 = [3, 5, 3, 5, 8, 5, 7, 3, 4, 3, 6, 7, 3, 4]

# Rate of Speech Respiration (iRBD Patients to Healthy Controls) | Insignificant

rsrScoreReading2 = [15.16, 20.63, 17.17, 23.09, 17.47, 20.62, 21.43, 12.92, 18.13, 19.27, 21.83, 11.93, 14.74, 15.78]
rsrScoreMonologue2 = [18.02, 17.52, 21.66, 18.07, 18.19, 21.5, 18.9, 22.39, 19.94, 20.93, 24.02, 13.79, 15.51, 6.04]

rsrScoreReading3 = [9.94, 8.87, 21.75, 17.69, 16.1, 5.76, 6.61, 21.64, 18.06, 17.84, 22.91, 11.81, 19.11, 17.57]
rsrScoreMonologue3 = [18.23, 13.89, 17.8, 18.67, 15.48, 9.76, 11.35, 25.86, 19.31, 20.13, 18.08, 15.35, 19.51, 14.04]

# Latency of Respiratory Exchange (iRBD Patients to Healthy Controls) | Insignificant

lreScoreReading2 = [117, 88, 180, 169, 196, 166, 128, 102, 75, 80, 121, 182, 42, 69]
lreScoreMonologue2 = [266, 58, 112, 216, 165, 128, 195, 96, 15, 128, 93, 144, 80, 90]

lreScoreReading3 = [57, 138, 106, 189, 91, 124, 234, 97, 183, 184, 129, 441, 251, 158]
lreScoreMonologue3 = [116, 58, 50, 229, 140, 92, 44, 55, 129, 120, 145, 144, 156, 130]


                                                            # PD Patients To iRBD Patients

# Entropy of Speech Timing (PD Patients to iRBD Patients) | Insignificant

estScoreReading = [1.564, 1.543, 1.553, 1.546, 1.573, 1.559]
estScoreMonologue = [1.564, 1.56, 1.518, 1.56, 1.572, 1.562]

# Rate of Speech Timing (PD Patients to iRBD Patients) | Insignificant

rstScoreReading = [354, 269, 317, 283, 340, 289]
rstScoreMonologue = [330, 230, 181, 208, 261, 325]

# Acceleration of Speech Timing (PD Patients to iRBD Patients) | Insignificant

astScoreReading = [6.05, 6.72, 24.19, 10.09, 14.94, 18.4]
astScoreMonologue = [-2.82, 11.77, 13.38, 1, -7.02, 3.57]

# Duration of Pause Intervals (PD Patients to iRBD Patients) | Insignificant

dpiScoreReading = [146, 211, 186, 183, 154, 174]
dpiScoreMonologue = [158, 206, 611, 374, 243, 201]

# Duration of Voiced Intervals (PD Patients to iRBD Patients) | Insignificant

dviScoreReading = [264, 328, 286, 317, 258, 303]
dviScoreMonologue = [318, 480, 398, 397, 308, 287]

# Gaping In-Between Voiced Intervals (PD Patients to iRBD Patients) | Insignificant

gibviScoreReading = [58.65, 42.9, 43.83, 43.53, 76.58, 52.25]
gibviScoreMonologue = [49.01, 33.54, 18.18, 36.21, 51.58, 43.29]

# Duration of Unvoiced Stops (PD Patients to iRBD Patients) | Insignificant

dusScoreReading = [31.38, 47.12, 33.63, 41.5, 22.38, 47.13]
dusScoreMonologue = [22.37, 26.87, 49.37, 26.88, 20.13, 22.38]

# Duration of Unvoiced Fricatives (PD Patients to iRBD Patients) | Insignificant

dufScoreReading = [-2.101, -0.973, 0.921, -0.989, -1.413, -0.151]
dufScoreMonologue = [0.588, 0.075, 1.488, -0.707, 0.254, 0.019]

# Relative Loudness of Respiration (PD Patients to iRBD Patients) | Insignificant

rlrScoreReading = [-22.47, -22.61, -25, -22.98, -20.32, -28.5]
rlrScoreMonologue = [-19.77, -22.32, -25.08, -24.08, -17.7, -21.63]

# Pause Intervals per Respiration (PD Patients to iRBD Patients) | Insignificant

piprScoreReading = [4.5, 5, 2.75, 3.5, 18.5, 5.5]
piprScoreMonologue = [6, 5, 2, 3, 6, 4]

# Rate of Speech Respiration (PD Patients to iRBD Patients) | Insignificant

rsrScoreReading = [21.14, 16.26, 27.07, 21.34, 5.22, 17.63]
rsrScoreMonologue = [13.81, 14.61, 18.21, 18.56, 17.47, 24.84]

# Latency of Respiratory Exchange (PD Patients to iRBD Patients) | Reading Scores Are Insignificant, Monologue Scores Are Significant

lreScoreReading = [167, 78, 124, 166, 172, 99]
lreScoreMonologue = [127, 151, 593, 174, 262, 139]


                                                            # PD Patients To Healthy Controls

# Entropy of Speech Timing (PD Patients to Healthy Controls) | Insignificant
# Rate of Speech Timing (PD Patients to Healthy Controls) | Insignificant, but p-value is ~5.77% (stat = -2.0271) for Reading
# Acceleration of Speech Timing (PD Patients to Healthy Controls) | Insignificant
# Duration of Pause Intervals (PD Patients to Healthy Controls) | Insignificant, but p-value is ~5.2% (stat = 2.0803) for Reading
# Duration of Voiced Intervals (PD Patients to Healthy Controls) | Reading Scores Are Insignificant, Monologue Scores Are Significant
# Gaping In-Between Voiced Intervals (PD Patients to Healthy Controls) | Insignificant
# Duration of Unvoiced Stops (PD Patients to Healthy Controls) | Insignificant
# Duration of Unvoiced Fricatives (PD Patients to Healthy Controls) | Insignificant
# Relative Loudness of Respiration (PD Patients to Healthy Controls) | Insignificant
# Pause Intervals per Respiration (PD Patients to Healthy Controls) | Insignificant
# Rate of Speech Respiration (PD Patients to Healthy Controls) | Insignificant
# Latency of Respiratory Exchange (PD Patients to Healthy Controls) | Reading Scores Are Insignificant, Monologue Scores Are Significant

result = ttest_ind(lreScoreReading, lreScoreReading3)
print(result)