# -*- coding: utf-8 -*-
"""Older Cohort Mann-Whitney U Tests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBSxr3L2ODAVL1Xg5zoJ7lSFHroZrPaO
"""

from scipy.stats import mannwhitneyu

# PD Patients to iRBD Patients

# Entropy of Speech Timing (PD Patients to iRBD Patients) | Insignificant

estScoreReading = [1.564, 1.55, 1.519, 1.563, 1.552, 1.537, 1.555, 1.563, 1.566, 1.56, 1.558, 1.446, 1.564, 1.556, 1.543]
estScoreMonologue = [1.569, 1.55, 1.539, 1.566, 1.559, 1.528, 1.573, 1.563, 1.569, 1.515, 1.555, 1.564, 1.561, 1.566, 1.558]

estScoreReading2 = [1.558, 1.565, 1.534, 1.569, 1.574, 1.54, 1.541, 1.555, 1.567, 1.561, 1.556, 1.572, 1.552, 1.56, 1.527, 1.555, 1.554, 1.562, 1.501, 1.554, 1.574]
estScoreMonologue2 = [1.564, 1.548, 1.541, 1.573, 1.552, 1.555, 1.535, 1.558, 1.552, 1.565, 1.56, 1.557, 1.559, 1.557, 1.512, 1.536, 1.559, 1.558, 1.53, 1.554, 1.575]

# Rate of Speech Timing (PD Patients to iRBD Patients) | Insignificant

rstScoreReading = [340, 211, 140, 269, 374, 234, 338, 347, 339, 298, 312, 340, 311, 325, 376]
rstScoreMonologue = [285, 247, 112, 289, 288, 174, 273, 279, 324, 278, 283, 277, 200, 372, 275]

rstScoreReading2 = [352, 331, 329, 360, 398, 232, 359, 279, 339, 289, 318, 288, 338, 301, 309, 291, 264, 320, 215, 354, 327]
rstScoreMonologue2 = [359, 258, 332, 322, 282, 248, 302, 233, 253, 266, 231, 238, 259, 302, 202, 235, 390, 270, 144, 338, 339]

# Acceleration of Speech Timing (PD Patients to iRBD Patients) | Insignificant

astScoreReading = [27.52, 11.97, -2.49, 2.47, 11.1, 21.82, -12.49, 23.14, 15.12, 17.84, 17.27, 7.56, 11.41, 6.64, -4.25]
astScoreMonologue = [8.2, 4.71, -9.09, -1.53, 5.25, 1.1, 11.04, 8.41, -5.26, -2.82, -1.06, 7.36, 2.41, 7.91, 10.82]

astScoreReading2 = [24.26, 3.5, 2.73, 12.47, 24.24, 11.3, 22.56, 3.36, 10.54, 15.8, 9.34, 8.19, 16.21, 20.72, -2.49, 2.94, 14.89, 11.32, 2.85, 11.18, 16.59]
astScoreMonologue2 = [-2.33, -4.41, 4.51, 0.23, 6.53, -2.02, 9.03, 4.1, 1.4, 5.48, -2.44, 5.36, 0.95, -6.13, -3.03, 1.52, 4.02, 2.23, 3.85, -1.97, 5.3]

# Duration of Pause Intervals (PD Patients to iRBD Patients) | Insignificant

dpiScoreReading = [173, 377, 360, 214, 117, 198, 146, 153, 146, 187, 140, 193, 220, 172, 169]
dpiScoreMonologue = [295, 280, 397, 251, 194, 433, 295, 322, 198, 320, 224, 202, 417, 138, 193]

dpiScoreReading2 = [133, 153, 145, 130, 140, 257, 124, 201, 132, 187, 166, 184, 179, 158, 190, 142, 203, 179, 388, 130, 190]
dpiScoreMonologue2 = [135, 296, 146, 183, 280, 292, 189, 237, 264, 305, 247, 293, 274, 231, 384, 297, 140, 202, 379, 143, 178]

# Duration of Voiced Intervals (PD Patients to iRBD Patients) | Insignificant

dviScoreReading = [253, 322, 663, 310, 265, 414, 296, 257, 270, 313, 285, 276, 267, 276, 332]
dviScoreMonologue = [264, 317, 800, 278, 317, 519, 264, 264, 258, 316, 310, 332, 358, 258, 349]

dviScoreReading2 = [259, 268, 282, 266, 234, 354, 247, 328, 302, 300, 303, 335, 264, 296, 291, 332, 348, 266, 418, 272, 252]
dviScoreMonologue2 = [268, 342, 298, 322, 279, 326, 313, 381, 351, 289, 437, 345, 310, 235, 440, 354, 269, 322, 671, 307, 260]

# Gaping In-Between Voiced Intervals (PD Patients to iRBD Patients) | Insignificant

gibviScoreReading = [48.26, 47.54, 13.72, 60.3, 52.5, 26.7, 38.03, 67.68, 77.13, 38.79, 49.76, 48.5, 57.92, 65.18, 60.58]
gibviScoreMonologue = [40.56, 48.97, 18.69, 58.9, 53.72, 23.55, 57.91, 44.66, 60.9, 29.35, 34.77, 47.43, 41.74, 61.78, 51.01]

gibviScoreReading2 = [79.46, 70.14, 35.79, 56.15, 72.55, 34.16, 77.28, 41.09, 55.47, 52.05, 45.84, 59.87, 39.21, 47.42, 34.28, 59.43, 45.95, 57.98, 20.52, 48.63, 75.91]
gibviScoreMonologue2 = [63, 43.84, 34.94, 53.33, 39.52, 43.72, 39.38, 36.52, 38.37, 43.59, 44.28, 39.23, 34.53, 59.1, 16.62, 40.03, 54.93, 63.1, 14.68, 38.18, 74.16]

# Duration of Unvoiced Stops (PD Patients to iRBD Patients) | Insignificant

dusScoreReading = [22.38, 38.12, 44.88, 20.12, 23.5, 41.5, 24.63, 26.87, 31.38, 31.38, 22.38, 32.5, 34.75, 22.37, 29.12]
dusScoreMonologue = [26.88, 22.37, 49.37, 22.38, 31.37, 40.37, 31.38, 35.87, 22.37, 35.87, 22.38, 20.13, 31.37, 17.88, 35.88]

dusScoreReading2 = [48.25, 31.38, 24.63, 37, 20.13, 40.38, 42.63, 24.62, 28, 29.12, 24.62, 29.12, 26.88, 24.62, 28, 20.13, 26.88, 29.13, 50.5, 29.12, 26.88]
dusScoreMonologue2 = [22.37, 35.88, 26.88, 22.38, 31.37, 35.88, 31.37, 26.87, 31.37, 20.13, 26.87, 31.38, 26.88, 31.37, 49.37, 58.37, 17.88, 22.37, 40.37, 22.37, 22.37]

# Decay of Unvoiced Fricatives (PD Patients to iRBD Patients) | Insignificant

dufScoreReading = [-1.745, 2.657, -0.934, -5.347, 0.269, -3.38, -1.835, -5.548, -6.643, -3.22, -5.404, -0.751, -0.519, -3.641, 5.825]
dufScoreMonologue = [-0.825, -0.955, 0.791, 0.174, -0.614, -0.179, 0.724, -0.76, 0.317, -0.088, -0.32, 0.208, 0.624, 0.207, 0.884]

dufScoreReading2 = [5.825, -2.752, -2.334, -3.499, -3.837, -8.238, 1.711, 2.353, 0.396, -0.001, -2.057, -1.172, -4.43, 1.359, 1.079, -12.591, -0.102, -2.824, -0.619, -6.67, -1.157]
dufScoreMonologue2 = [0.761, 0.578, -0.446, -0.199, 0.815, -0.853, 0.13, 0.581, -0.073, -0.513, 1.119, -0.918, -0.834, -0.186, -0.857, -0.286, 0.139, 0.116, 0.039, 0.555, -0.318]

# Relative Loudness of Respiration (PD Patients to iRBD Patients) | Insignificant

rlrScoreReading = [-24.59, -16.89, -25.54, -26.2, -15.04, -20.73, -22.59, -24.66, -18.34, -24.43, -25, -21.29, -24.1, -21.86, -22.91]
rlrScoreMonologue = [-23.26, -13.29, -25.08, -23.38, -17.04, -22.97, -19.23, -22.32, -15.8, -25.14, -20.82, -17.8, -21.57, -19.67, -20.52]

rlrScoreReading2 = [-18.31, -19.67, -22.39, -20.89, -22.84, -21.2, -23.7, -22.22, -18.38, -22.8, -22.86, -20.76, -18.65, -16.97, -26.48, -23.67, -19.17, -22.68, -24.45, -23.44, -22.02]
rlrScoreMonologue2 = [-17.66, -17.12, -21.28, -20.96, -18, -20.36, -20.3, -20.27, -17.27, -21.41, -19.72, -20.42, -22.43, -11.81, -23.06, -23.53, -18.47, -19.77, -24.31, -21.27, -16.02]

# Pause Intervals per Respiration (PD Patients to iRBD Patients) | Insignificant

piprScoreReading = [7, 3, 1, 5.25, 9.25, 3, 5.5, 5.5, 6, 7, 4.75, 2.5, 4, 4.5, 5.75]
piprScoreMonologue = [4, 4, 2, 5, 4, 2, 5, 3.5, 6, 3, 5, 4, 2, 5, 5]

piprScoreReading2 = [5.5, 7.75, 5.5, 8.25, 6.25, 1.5, 9, 4, 3.75, 5, 4.5, 6, 4, 6.75, 3, 6.75, 4, 5.5, 1, 4.25, 7]
piprScoreMonologue2 = [7, 3, 5, 5.5, 2, 3, 5, 3, 4, 4, 3, 3, 5, 3, 2, 3, 6, 6, 1.5, 5, 5]

# Rate of Speech Respiration (PD Patients to iRBD Patients) | Insignificant

rsrScoreReading = [15.28, 20.76, 18.71, 16.33, 12.75, 24.68, 13.67, 16.76, 15.8, 11.63, 16.91, 14.51, 17.92, 21.87, 17.61]
rsrScoreMonologue = [21.77, 22.52, 14.37, 17.85, 21.25, 18.99, 16.5, 20.06, 18.86, 19.11, 14.55, 14.93, 21.42, 17.99, 13.63]

rsrScoreReading2 = [19.2, 21.17, 14.14, 15.39, 19.27, 25.67, 11.19, 19.46, 16.64, 16.78, 20.08, 13.56, 20.82, 14.09, 19.07, 16.94, 17.05, 19.07, 29.16, 20.43, 15.3]
rsrScoreMonologue2 = [14.56, 19.12, 14.6, 15.72, 16.87, 24.26, 10.79, 17.91, 13.33, 19.71, 17.38, 23.22, 14.24, 28.88, 16.32, 17.95, 17.65, 16.46, 21, 15.44, 24.07]

# Latency of Respiratory Exchange (PD Patients to iRBD Patients) | Insignificant

lreScoreReading = [163, 372, 119, 288, 87, 44, 131, 200, 142, 79, 81, 92, 192, 146, 114]
lreScoreMonologue = [313, 201, 151, 203, 81, 40, 193, 218, 202, 174, 118, 105, 248, 100, 96]

lreScoreReading2 = [79, 89, 76, 87, 85, 154, 180, 181, 65, 120, 167, 167, 142, 125, 200, 155, 158, 113, 10, 65, 148]
lreScoreMonologue2 = [82, 85, 71, 161, 127, 185, 124, 219, 282, 365, 209, 98, 208, 323, 93, 102, 70, 128, 52, 69, 117]



# PD Patients To Healthy Controls

# Entropy of Speech Timing (PD Patients to Healthy Controls) | Insignificant

estScoreReading3 = [1.546, 1.524, 1.548, 1.543, 1.553, 1.565, 1.559, 1.542, 1.563, 1.559, 1.545, 1.561, 1.559, 1.547, 1.566, 1.563, 1.542, 1.555, 1.553, 1.57, 1.539, 1.563, 1.56, 1.565, 1.55, 1.554, 1.56, 1.557, 1.564, 1.547]
estScoreMonologue3 = [1.539, 1.558, 1.567, 1.541, 1.576, 1.564, 1.555, 1.566, 1.568, 1.565, 1.544, 1.567, 1.566, 1.551, 1.56, 1.536, 1.547, 1.553, 1.56, 1.558, 1.563, 1.569, 1.561, 1.564, 1.563, 1.56, 1.564, 1.552, 1.554, 1.569]

# Rate of Speech Timing (PD Patients to Healthy Controls) | Monologue Scores Are Significant, Reading Scores Are Not

rstScoreReading3 = [249, 319, 347, 360, 336, 403, 359, 346, 357, 363, 241, 342, 395, 376, 350, 361, 279, 337, 343, 402, 303, 353, 336, 299, 382, 321, 315, 323, 265, 291]
rstScoreMonologue3 = [241, 342, 333, 265, 367, 393, 316, 307, 343, 337, 233, 346, 344, 400, 351, 353, 316, 360, 302, 368, 309, 346, 298, 245, 359, 297, 181, 274, 254, 300]

# Acceleration of Speech Timing (PD Patients to Healthy Controls) | Insignificant

astScoreReading3 = [25.8, 12.82, 32.06, 13, 6.16, 17.55, 13.67, 14.13, 7.32, -10.52, 19.57, 12.58, 8.09, 18.34, 9.57, 20.36, 10.43, 14.51, -2.26, 13.71, -9.85, -7.45, -3.45, -7.17, 33.64, 1.42, 20.01, 33.94, 3.58, 6.31]
astScoreMonologue3 = [3.69, -1.28, -0.98, 14.64, 8.71, 3.6, 3.92, 0.49, -1.42, 5.26, -0.62, 1.71, -1.66, 1.4, 5.07, 3.2, 1.48, 1.84, 0.44, 2.7, 0.1, -3.18, 0.7, 0.83, 0.22, -0.04, -5.38, 1.32, 8.43, 4.09]

# Duration of Pause Intervals (PD Patients to Healthy Controls) | Monologue and Reading Scores Are Significant

dpiScoreReading3 = [185, 149, 148, 134, 162, 130, 139, 139, 147, 143, 191, 164, 118, 148, 160, 117, 244, 156, 158, 119, 163, 153, 128, 144, 121, 156, 158, 139, 198, 183]
dpiScoreMonologue3 = [269, 199, 180, 142, 151, 147, 157, 130, 161, 173, 255, 176, 166, 174, 207, 164, 247, 129, 170, 166, 200, 177, 177, 220, 143, 178, 460, 193, 264, 177]

# Duration of Voiced Intervals (PD Patients to Healthy Controls) | Insignificant

dviScoreReading3 = [366, 290, 245, 284, 252, 229, 266, 285, 254, 281, 362, 262, 232, 221, 244, 264, 318, 271, 254, 234, 297, 257, 288, 346, 237, 281, 277, 292, 365, 359]
dviScoreMonologue3 = [381, 242, 278, 392, 264, 238, 324, 380, 293, 290, 367, 261, 267, 216, 242, 269, 281, 288, 331, 255, 288, 267, 330, 373, 265, 318, 357, 328, 380, 359]

# Gaping In-Between Voiced Intervals (PD Patients to Healthy Controls) | Insignificant

gibviScoreReading3 = [43.86, 34.35, 50.68, 41.17, 73.84, 64.32, 42.87, 49.91, 65.13, 44.38, 42.66, 48.84, 58.42, 63.04, 66, 70.8, 32.94, 44.12, 56.64, 88.23, 35.99, 60.9, 62.66, 54.81, 69.17, 52.85, 73.93, 57.45, 40.25, 39.59]
gibviScoreMonologue3 = [27.91, 72.96, 60.97, 36.95, 59.11, 65.63, 42.14, 50.9, 59.15, 48.09, 39.71, 53.6, 56.52, 46.17, 52.93, 49.15, 37.1, 31.93, 39.34, 46.84, 52.21, 57.01, 47.25, 48.15, 57.28, 52.53, 41.14, 50.61, 36.36, 47.06]

# Duration of Unvoiced Stops (PD Patients to Healthy Controls) | Insignificant, but Monologue Scores have a p-value of ~0.0581

dusScoreReading3 = [34.75, 49.38, 40.38, 23.5, 21.25, 24.62, 23.5, 29.13, 26.88, 29.12, 44.88, 29.12, 26.88, 26.88, 37, 22.37, 38.13, 21.25, 31.38, 21.25, 21.25, 21.25, 26.87, 33.63, 51.63, 20.13, 29.13, 24.62, 26.88, 31.37]
dusScoreMonologue3 = [29.13, 17.88, 17.88, 26.87, 17.88, 26.87, 22.38, 22.37, 22.37, 31.37, 31.38, 22.37, 31.37, 22.38, 26.88, 26.87, 26.88, 22.37, 22.38, 26.87, 22.37, 17.88, 17.88, 35.88, 22.37, 22.38, 40.37, 13.37, 26.88, 22.37]

# Decay of Unvoiced Fricatives (PD Patients to Healthy Controls) | Insignifcant

dufScoreReading3 = [-0.078, 2.341, -1.987, -6.035, -3.201, -11.27, -5.017, 1.905, -3.01, 0.352, -0.123, -2.191, -6.663, -1.518, -3.007, -2.522, -3.965, 0.236, -1.066, -8.685, -4.084, -1.998, -5.26, 0.139, -1.588, 2.971, 2.94, 2.226, -1.872, -1.517]
dufScoreMonologue3 = [0.335, 0.135, -1.003, -0.687, -0.338, 0.127, -0.837, 0.339, -0.245, 1.323, 0.029, 0.435, 0.019, 0.319, -0.538, -0.574, -0.059, -0.153, -0.786, -0.366, -0.484, -0.141, -1.088, 0.677, -0.165, 0.42, -1.417, 0.046, 0.023, -0.117]

# Relative Loudness of Respiration (PD Patients to Healthy Controls) | Insignifcant

rlrScoreReading3 = [-26.25, -22.96, -22.52, -19.92, -25.72, -15.27, -22.24, -25.85, -20.38, -18.42, -23.24, -21.43, -22.86, -22.43, -16.24, -21.27, -26.49, -24.83, -22.59, -22.65, -29.67, -22.2, -25.44, -23.66, -20.67, -23.41, -24.34, -24.76, -28.04, -22.87]
rlrScoreMonologue3 = [-25.79, -18.61, -21.09, -22.15, -22.21, -9.27, -22.63, -22.34, -17.34, -12.78, -24.14, -19.24, -17.74, -20.85, -13.67, -20.02, -20.81, -16.47, -20.2, -21.36, -25.41, -19.24, -22.73, -21.51, -19.81, -22.66, -23.68, -20.7, -23.12, -18.67]

# Pause Intervals per Respiration (PD Patients to Healthy Controls) | Insignificant, but Monologue Scores have a p-value of ~0.0581

piprScoreReading3 = [4.5, 4, 5.75, 5, 6, 5.25, 4.5, 5, 5.5, 7.25, 3.5, 4.5, 6, 4, 4, 7.5, 3.25, 5, 4.5, 8, 3, 5, 5.5, 5.25, 7.25, 8, 9.5, 5.5, 6.5, 5]
piprScoreMonologue3 = [2, 3, 3.5, 5, 10.5, 5, 4, 7, 6, 7, 4, 4, 6, 6, 3, 5, 4, 5, 4, 6, 5, 4.5, 6, 6, 5, 7, 4, 4.5, 3, 5]

# Rate of Speech Respiration (PD Patients to Healthy Controls) | Insignificant

rsrScoreReading3 = [22.24, 15.56, 19.77, 16.18, 19.6, 40.22, 21.05, 16.66, 17.7, 11.48, 23.46, 22.76, 21.01, 24.03, 35.03, 14.75, 18.11, 19.61, 23.08, 15.97, 23.25, 21.35, 19.04, 17.77, 28.85, 9.84, 9.53, 16.5, 10.24, 13.46]
rsrScoreMonologue3 = [18.49, 24.95, 21.51, 9, 9.24, 17.7, 20.23, 11.08, 13.29, 14.82, 15.9, 19.21, 12.54, 18.19, 21.44, 11.26, 16.53, 16.72, 19.72, 14.72, 19.75, 21.03, 12.65, 13.12, 16.09, 13.5, 14.44, 19.54, 15.41, 16.94]

# Latency of Respiratory Exchange (PD Patients to Healthy Controls) | Insignificant

lreScoreReading3 = [118, 117, 182, 84, 214, 175, 106, 101, 171, 325, 156, 95, 53, 73, 54, 134, 112, 113, 89, 165, 144, 108, 85, 113, 117, 171, 308, 141, 158, 224]
lreScoreMonologue3 = [128, 150, 140, 51, 240, 108, 75, 83, 122, 70, 250, 72, 104, 86, 84, 75, 205, 71, 97, 201, 144, 124, 33, 100, 77, 169, 522, 138, 177, 138]



# iRBD Patients To Healthy Controls

# Entropy of Speech Timing (iRBD Patients to Healthy Controls) | Insignificant, but Monologue Scores have a p-value of ~0.0644
# Rate of Speech Timing (iRBD Patients to Healthy Controls) | Monologue Scores Are Significant, though Reading Scores have a p-value of ~0.0703
# Acceleration of Speech Timing (iRBD Patients to Healthy Controls) | Insignificant
# Duration of Pause Intervals (iRBD Patients to Healthy Controls) | Monologue Scores Are Significant, Reading Scores Are Not
# Duration of Voiced Intervals (iRBD Patients to Healthy Controls) | Insignificant
# Gaping In-Between Voiced Intervals (iRBD Patients to Healthy Controls) | Insignificant
# Duration of Unvoiced Stops (iRBD Patients to Healthy Controls) | Monologue Scores Are Significant, Reading Scores Are Not
# Decay of Unvoiced Fricatives (iRBD Patients to Healthy Controls) | Insignificant
# Relative Loudness of Respiration (iRBD Patients to Healthy Controls) | Insignificant
# Pause Intervals per Respiration (iRBD Patients to Healthy Controls) | Monologue Scores Are Significant
# Rate of Speech Respiration (iRBD Patients to Healthy Controls) | Insignificant
# Latency of Respiratory Exchange (iRBD Patients to Healthy Controls) | Insignificant

U1, p_value = mannwhitneyu(lreScoreReading2, lreScoreReading3, method = "exact")
nx, ny = len(lreScoreReading2), len(lreScoreReading3)
U2 = nx * ny - U1

print(f"iRBD Patients: {U1}")
print(f"Healthy Controls: {U2}")
print(f"P-Value: {p_value}")